# Generated by Django 4.2.6 on 2024-12-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_alter_image_description'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.UniqueConstraint(fields=('image',), name='unique_annotation_per_image'),
        ),
    ]
